language: swift
osx_image: xcode13
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=LabelKit.xcodeproj
  # Framework targets
  - FRAMEWORK_SCHEME_IOS="LabelKit iOS"
  - FRAMEWORK_SCHEME_TVOS="LabelKit tvOS"
  # Example targets
  - EXAMPLE_SCHEME_IOS="LabelKit Example iOS"
  - EXAMPLE_SCHEME_TVOS="LabelKit Example tvOS"
  
  matrix:
    - DESTINATION="OS=15.0,name=iPhone 13 Pro"           SCHEME="$FRAMEWORK_SCHEME_IOS"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" EXAMPLE_SCHEME="$EXAMPLE_SCHEME_IOS"   POD_LINT="YES"
    - DESTINATION="OS=13.5,name=iPhone 11 Pro"           SCHEME="$FRAMEWORK_SCHEME_IOS"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" EXAMPLE_SCHEME="$EXAMPLE_SCHEME_IOS"   POD_LINT="NO"
    - DESTINATION="OS=12.2,name=iPhone Xs"               SCHEME="$FRAMEWORK_SCHEME_IOS"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" EXAMPLE_SCHEME="$EXAMPLE_SCHEME_IOS"   POD_LINT="NO"
    - DESTINATION="OS=12.2,name=Apple TV 4K (at 1080p)"  SCHEME="$FRAMEWORK_SCHEME_TVOS"    RUN_TESTS="YES" BUILD_EXAMPLE="YES" EXAMPLE_SCHEME="$EXAMPLE_SCHEME_TVOS"  POD_LINT="NO"
    - DESTINATION="OS=13.4,name=Apple TV 4K"             SCHEME="$FRAMEWORK_SCHEME_TVOS"    RUN_TESTS="YES" BUILD_EXAMPLE="YES" EXAMPLE_SCHEME="$EXAMPLE_SCHEME_TVOS"  POD_LINT="NO" 

before_install:
  - gem install cocoapods --no-document --quiet
  
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
        xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
    
  # Build Framework in Release and Run Tests if specified
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    
  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
        xcodebuild -project "$PROJECT" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
    
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
        pod lib lint;
    fi
